import { create } from "zustand";

export interface Student {
    id: number,
    grade: number,
    class: number,
    name: string,
}

interface StudnetStoreType {
    // grades: number[],
    // classes: { [key: number]: number[] },
    students: { [key: number]: { [key: number]: Student[] } }
}

export const useStudentStore = create<StudnetStoreType>()(set => ({
    // grades: [1,2,3],
    // classes: {
    //     [1]: [1,2,3,4],
    //     [2]: [1,2,3,4],
    //     [3]: [1,2,3,4]
    // },
    students: { // 가짜 데이터 (테스트용 가리치킨)
        1: {
          1: [{ 'id': 1101, 'grade': 1, 'class': 1, 'name': '김지우' },
          { 'id': 1102, 'grade': 1, 'class': 1, 'name': '김지훈' },
          { 'id': 1103, 'grade': 1, 'class': 1, 'name': '이지훈' },
          { 'id': 1104, 'grade': 1, 'class': 1, 'name': '장수아' },
          { 'id': 1105, 'grade': 1, 'class': 1, 'name': '김수아' },
          { 'id': 1106, 'grade': 1, 'class': 1, 'name': '조하은' },
          { 'id': 1107, 'grade': 1, 'class': 1, 'name': '최예준' },
          { 'id': 1108, 'grade': 1, 'class': 1, 'name': '이민수' },
          { 'id': 1109, 'grade': 1, 'class': 1, 'name': '윤서연' },
          { 'id': 1110, 'grade': 1, 'class': 1, 'name': '김지우' },
          { 'id': 1111, 'grade': 1, 'class': 1, 'name': '정서연' },
          { 'id': 1112, 'grade': 1, 'class': 1, 'name': '윤지우' },
          { 'id': 1113, 'grade': 1, 'class': 1, 'name': '최서윤' },
          { 'id': 1114, 'grade': 1, 'class': 1, 'name': '정수아' },
          { 'id': 1115, 'grade': 1, 'class': 1, 'name': '박수아' },
          { 'id': 1116, 'grade': 1, 'class': 1, 'name': '최서연' },
          { 'id': 1117, 'grade': 1, 'class': 1, 'name': '이도윤' },
          { 'id': 1118, 'grade': 1, 'class': 1, 'name': '조민수' },
          { 'id': 1119, 'grade': 1, 'class': 1, 'name': '장서연' },
          { 'id': 1120, 'grade': 1, 'class': 1, 'name': '강하은' },
          { 'id': 1121, 'grade': 1, 'class': 1, 'name': '강도윤' }],
          2: [{ 'id': 1201, 'grade': 1, 'class': 2, 'name': '임예준' },
          { 'id': 1202, 'grade': 1, 'class': 2, 'name': '윤지훈' },
          { 'id': 1203, 'grade': 1, 'class': 2, 'name': '강도윤' },
          { 'id': 1204, 'grade': 1, 'class': 2, 'name': '박하은' },
          { 'id': 1205, 'grade': 1, 'class': 2, 'name': '정예준' },
          { 'id': 1206, 'grade': 1, 'class': 2, 'name': '정지훈' },
          { 'id': 1207, 'grade': 1, 'class': 2, 'name': '이도윤' },
          { 'id': 1208, 'grade': 1, 'class': 2, 'name': '윤예준' },
          { 'id': 1209, 'grade': 1, 'class': 2, 'name': '김민수' },
          { 'id': 1210, 'grade': 1, 'class': 2, 'name': '조도윤' },
          { 'id': 1211, 'grade': 1, 'class': 2, 'name': '조서연' },
          { 'id': 1212, 'grade': 1, 'class': 2, 'name': '윤민수' },
          { 'id': 1213, 'grade': 1, 'class': 2, 'name': '조지우' },
          { 'id': 1214, 'grade': 1, 'class': 2, 'name': '강예준' },
          { 'id': 1215, 'grade': 1, 'class': 2, 'name': '이도윤' },
          { 'id': 1216, 'grade': 1, 'class': 2, 'name': '장수아' }],
          3: [{ 'id': 1301, 'grade': 1, 'class': 3, 'name': '임서연' },
          { 'id': 1302, 'grade': 1, 'class': 3, 'name': '최수아' },
          { 'id': 1303, 'grade': 1, 'class': 3, 'name': '임민수' },
          { 'id': 1304, 'grade': 1, 'class': 3, 'name': '이지훈' },
          { 'id': 1305, 'grade': 1, 'class': 3, 'name': '최수아' },
          { 'id': 1306, 'grade': 1, 'class': 3, 'name': '윤현우' },
          { 'id': 1307, 'grade': 1, 'class': 3, 'name': '이지훈' },
          { 'id': 1308, 'grade': 1, 'class': 3, 'name': '이수아' },
          { 'id': 1309, 'grade': 1, 'class': 3, 'name': '장수아' },
          { 'id': 1310, 'grade': 1, 'class': 3, 'name': '최서윤' },
          { 'id': 1311, 'grade': 1, 'class': 3, 'name': '정서윤' },
          { 'id': 1312, 'grade': 1, 'class': 3, 'name': '이서연' },
          { 'id': 1313, 'grade': 1, 'class': 3, 'name': '장도윤' },
          { 'id': 1314, 'grade': 1, 'class': 3, 'name': '윤서연' },
          { 'id': 1315, 'grade': 1, 'class': 3, 'name': '최서연' },
          { 'id': 1316, 'grade': 1, 'class': 3, 'name': '정예준' },
          { 'id': 1317, 'grade': 1, 'class': 3, 'name': '임서윤' },
          { 'id': 1318, 'grade': 1, 'class': 3, 'name': '정현우' },
          { 'id': 1319, 'grade': 1, 'class': 3, 'name': '김도윤' },
          { 'id': 1320, 'grade': 1, 'class': 3, 'name': '윤지훈' },
          { 'id': 1321, 'grade': 1, 'class': 3, 'name': '조서윤' }],
          4: [{ 'id': 1401, 'grade': 1, 'class': 4, 'name': '최지훈' },
          { 'id': 1402, 'grade': 1, 'class': 4, 'name': '임현우' },
          { 'id': 1403, 'grade': 1, 'class': 4, 'name': '김서연' },
          { 'id': 1404, 'grade': 1, 'class': 4, 'name': '김서연' },
          { 'id': 1405, 'grade': 1, 'class': 4, 'name': '조도윤' },
          { 'id': 1406, 'grade': 1, 'class': 4, 'name': '박도윤' },
          { 'id': 1407, 'grade': 1, 'class': 4, 'name': '김지우' },
          { 'id': 1408, 'grade': 1, 'class': 4, 'name': '정수아' },
          { 'id': 1409, 'grade': 1, 'class': 4, 'name': '박서연' },
          { 'id': 1410, 'grade': 1, 'class': 4, 'name': '조지훈' },
          { 'id': 1411, 'grade': 1, 'class': 4, 'name': '장지훈' },
          { 'id': 1412, 'grade': 1, 'class': 4, 'name': '최지우' },
          { 'id': 1413, 'grade': 1, 'class': 4, 'name': '박예준' },
          { 'id': 1414, 'grade': 1, 'class': 4, 'name': '최지우' },
          { 'id': 1415, 'grade': 1, 'class': 4, 'name': '윤수아' }]
        },
        2: {
          1: [{ 'id': 2101, 'grade': 2, 'class': 1, 'name': '박민수' },
          { 'id': 2102, 'grade': 2, 'class': 1, 'name': '이예준' },
          { 'id': 2103, 'grade': 2, 'class': 1, 'name': '임지훈' },
          { 'id': 2104, 'grade': 2, 'class': 1, 'name': '장도윤' },
          { 'id': 2105, 'grade': 2, 'class': 1, 'name': '조도윤' },
          { 'id': 2106, 'grade': 2, 'class': 1, 'name': '박도윤' },
          { 'id': 2107, 'grade': 2, 'class': 1, 'name': '강예준' },
          { 'id': 2108, 'grade': 2, 'class': 1, 'name': '윤현우' },
          { 'id': 2109, 'grade': 2, 'class': 1, 'name': '최수아' },
          { 'id': 2110, 'grade': 2, 'class': 1, 'name': '최하은' },
          { 'id': 2111, 'grade': 2, 'class': 1, 'name': '장수아' },
          { 'id': 2112, 'grade': 2, 'class': 1, 'name': '박수아' },
          { 'id': 2113, 'grade': 2, 'class': 1, 'name': '김서윤' },
          { 'id': 2114, 'grade': 2, 'class': 1, 'name': '박하은' },
          { 'id': 2115, 'grade': 2, 'class': 1, 'name': '김예준' },
          { 'id': 2116, 'grade': 2, 'class': 1, 'name': '임도윤' },
          { 'id': 2117, 'grade': 2, 'class': 1, 'name': '이서윤' },
          { 'id': 2118, 'grade': 2, 'class': 1, 'name': '장도윤' },
          { 'id': 2119, 'grade': 2, 'class': 1, 'name': '조도윤' }],
          2: [{ 'id': 2201, 'grade': 2, 'class': 2, 'name': '임현우' },
          { 'id': 2202, 'grade': 2, 'class': 2, 'name': '최현우' },
          { 'id': 2203, 'grade': 2, 'class': 2, 'name': '박서연' },
          { 'id': 2204, 'grade': 2, 'class': 2, 'name': '정서연' },
          { 'id': 2205, 'grade': 2, 'class': 2, 'name': '임현우' },
          { 'id': 2206, 'grade': 2, 'class': 2, 'name': '임예준' },
          { 'id': 2207, 'grade': 2, 'class': 2, 'name': '임도윤' },
          { 'id': 2208, 'grade': 2, 'class': 2, 'name': '장서윤' },
          { 'id': 2209, 'grade': 2, 'class': 2, 'name': '박예준' },
          { 'id': 2210, 'grade': 2, 'class': 2, 'name': '임서연' }],
          3: [{ 'id': 2301, 'grade': 2, 'class': 3, 'name': '강민수' },
          { 'id': 2302, 'grade': 2, 'class': 3, 'name': '최수아' },
          { 'id': 2303, 'grade': 2, 'class': 3, 'name': '이하은' },
          { 'id': 2304, 'grade': 2, 'class': 3, 'name': '정서윤' },
          { 'id': 2305, 'grade': 2, 'class': 3, 'name': '이예준' },
          { 'id': 2306, 'grade': 2, 'class': 3, 'name': '박현우' },
          { 'id': 2307, 'grade': 2, 'class': 3, 'name': '김현우' },
          { 'id': 2308, 'grade': 2, 'class': 3, 'name': '김현우' },
          { 'id': 2309, 'grade': 2, 'class': 3, 'name': '이하은' },
          { 'id': 2310, 'grade': 2, 'class': 3, 'name': '장지훈' },
          { 'id': 2311, 'grade': 2, 'class': 3, 'name': '강현우' },
          { 'id': 2312, 'grade': 2, 'class': 3, 'name': '박도윤' },
          { 'id': 2313, 'grade': 2, 'class': 3, 'name': '박민수' },
          { 'id': 2314, 'grade': 2, 'class': 3, 'name': '임현우' },
          { 'id': 2315, 'grade': 2, 'class': 3, 'name': '윤수아' },
          { 'id': 2316, 'grade': 2, 'class': 3, 'name': '강하은' },
          { 'id': 2317, 'grade': 2, 'class': 3, 'name': '조예준' },
          { 'id': 2318, 'grade': 2, 'class': 3, 'name': '조예준' },
          { 'id': 2319, 'grade': 2, 'class': 3, 'name': '임하은' },
          { 'id': 2320, 'grade': 2, 'class': 3, 'name': '장서연' }],
          4: [{ 'id': 2401, 'grade': 2, 'class': 4, 'name': '정수아' },
          { 'id': 2402, 'grade': 2, 'class': 4, 'name': '장서연' },
          { 'id': 2403, 'grade': 2, 'class': 4, 'name': '최예준' },
          { 'id': 2404, 'grade': 2, 'class': 4, 'name': '김도윤' },
          { 'id': 2405, 'grade': 2, 'class': 4, 'name': '이서연' },
          { 'id': 2406, 'grade': 2, 'class': 4, 'name': '최도윤' },
          { 'id': 2407, 'grade': 2, 'class': 4, 'name': '윤서윤' },
          { 'id': 2408, 'grade': 2, 'class': 4, 'name': '강예준' },
          { 'id': 2409, 'grade': 2, 'class': 4, 'name': '윤현우' },
          { 'id': 2410, 'grade': 2, 'class': 4, 'name': '조민수' },
          { 'id': 2411, 'grade': 2, 'class': 4, 'name': '박수아' },
          { 'id': 2412, 'grade': 2, 'class': 4, 'name': '박서윤' },
          { 'id': 2413, 'grade': 2, 'class': 4, 'name': '임지훈' },
          { 'id': 2414, 'grade': 2, 'class': 4, 'name': '강지우' },
          { 'id': 2415, 'grade': 2, 'class': 4, 'name': '임민수' },
          { 'id': 2416, 'grade': 2, 'class': 4, 'name': '이민수' }]
        },
        3: {
          1: [{ 'id': 3101, 'grade': 3, 'class': 1, 'name': '박수아' },
          { 'id': 3102, 'grade': 3, 'class': 1, 'name': '박지우' },
          { 'id': 3103, 'grade': 3, 'class': 1, 'name': '정지우' },
          { 'id': 3104, 'grade': 3, 'class': 1, 'name': '윤민수' },
          { 'id': 3105, 'grade': 3, 'class': 1, 'name': '강하은' },
          { 'id': 3106, 'grade': 3, 'class': 1, 'name': '정지우' },
          { 'id': 3107, 'grade': 3, 'class': 1, 'name': '정지우' },
          { 'id': 3108, 'grade': 3, 'class': 1, 'name': '박서연' },
          { 'id': 3109, 'grade': 3, 'class': 1, 'name': '정민수' },
          { 'id': 3110, 'grade': 3, 'class': 1, 'name': '임하은' },
          { 'id': 3111, 'grade': 3, 'class': 1, 'name': '박서윤' },
          { 'id': 3112, 'grade': 3, 'class': 1, 'name': '최수아' },
          { 'id': 3113, 'grade': 3, 'class': 1, 'name': '윤지훈' },
          { 'id': 3114, 'grade': 3, 'class': 1, 'name': '이민수' },
          { 'id': 3115, 'grade': 3, 'class': 1, 'name': '강지우' },
          { 'id': 3116, 'grade': 3, 'class': 1, 'name': '이민수' },
          { 'id': 3117, 'grade': 3, 'class': 1, 'name': '임현우' },
          { 'id': 3118, 'grade': 3, 'class': 1, 'name': '이도윤' },
          { 'id': 3119, 'grade': 3, 'class': 1, 'name': '강지우' }],
          2: [{ 'id': 3201, 'grade': 3, 'class': 2, 'name': '박서윤' },
          { 'id': 3202, 'grade': 3, 'class': 2, 'name': '정수아' },
          { 'id': 3203, 'grade': 3, 'class': 2, 'name': '장민수' },
          { 'id': 3204, 'grade': 3, 'class': 2, 'name': '정예준' },
          { 'id': 3205, 'grade': 3, 'class': 2, 'name': '강하은' },
          { 'id': 3206, 'grade': 3, 'class': 2, 'name': '박민수' },
          { 'id': 3207, 'grade': 3, 'class': 2, 'name': '박현우' },
          { 'id': 3208, 'grade': 3, 'class': 2, 'name': '임민수' },
          { 'id': 3209, 'grade': 3, 'class': 2, 'name': '이지훈' },
          { 'id': 3210, 'grade': 3, 'class': 2, 'name': '정현우' },
          { 'id': 3211, 'grade': 3, 'class': 2, 'name': '김민수' },
          { 'id': 3212, 'grade': 3, 'class': 2, 'name': '최현우' },
          { 'id': 3213, 'grade': 3, 'class': 2, 'name': '윤민수' },
          { 'id': 3214, 'grade': 3, 'class': 2, 'name': '박지훈' },
          { 'id': 3215, 'grade': 3, 'class': 2, 'name': '장예준' }],
          3: [{ 'id': 3301, 'grade': 3, 'class': 3, 'name': '강예준' },
          { 'id': 3302, 'grade': 3, 'class': 3, 'name': '강하은' },
          { 'id': 3303, 'grade': 3, 'class': 3, 'name': '박현우' },
          { 'id': 3304, 'grade': 3, 'class': 3, 'name': '임민수' },
          { 'id': 3305, 'grade': 3, 'class': 3, 'name': '정지우' },
          { 'id': 3306, 'grade': 3, 'class': 3, 'name': '조예준' },
          { 'id': 3307, 'grade': 3, 'class': 3, 'name': '조예준' },
          { 'id': 3308, 'grade': 3, 'class': 3, 'name': '박민수' },
          { 'id': 3309, 'grade': 3, 'class': 3, 'name': '임지훈' },
          { 'id': 3310, 'grade': 3, 'class': 3, 'name': '정예준' }],
          4: [{ 'id': 3401, 'grade': 3, 'class': 4, 'name': '강예준' },
          { 'id': 3402, 'grade': 3, 'class': 4, 'name': '박민수' },
          { 'id': 3403, 'grade': 3, 'class': 4, 'name': '이도윤' },
          { 'id': 3404, 'grade': 3, 'class': 4, 'name': '임수아' },
          { 'id': 3405, 'grade': 3, 'class': 4, 'name': '김지우' },
          { 'id': 3406, 'grade': 3, 'class': 4, 'name': '강서연' },
          { 'id': 3407, 'grade': 3, 'class': 4, 'name': '강지훈' },
          { 'id': 3408, 'grade': 3, 'class': 4, 'name': '조지우' },
          { 'id': 3409, 'grade': 3, 'class': 4, 'name': '김현우' },
          { 'id': 3410, 'grade': 3, 'class': 4, 'name': '이도윤' },
          { 'id': 3411, 'grade': 3, 'class': 4, 'name': '정서윤' },
          { 'id': 3412, 'grade': 3, 'class': 4, 'name': '최민수' },
          { 'id': 3413, 'grade': 3, 'class': 4, 'name': '최현우' },
          { 'id': 3414, 'grade': 3, 'class': 4, 'name': '김도윤' }]
        }
      }
}));